apiVersion: v1
kind: Service
metadata:
  name: ftps-serv
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      name: ftp
      targetPort: 20
    - port: 21
      name: ftp-com
      targetPort: 21
    - port: 21000
      name: ftp-data
      targetPort: 21000