apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps-container
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21000
          volumeMounts:
            - name: ftps
              mountPath: /ftp_peer/
      volumes:
        - name: ftps
          persistentVolumeClaim:
            claimName: ftps-pvc